version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  # Add a database service if your application needs one
  # db:
  #   image: mongo:latest
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - app-network
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure

networks:
  app-network:
    driver: overlay

# volumes:
#   mongodb_data: 